name: Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x
      - run: yarn check
