name: Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x
          cache-dependency-path: "**/yarn.lock"
      - uses: actions/cache@v2
        with:
          path: .cache
          key: release-${{ runner.os }}-dist-${{ hashFiles('yarn.lock') }}
          restore-keys: release-${{ runner.os }}-dist-
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: dio
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
      - run: yarn dist
        env:
          PKG_CACHE_PATH: .cache
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

